services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./.air.toml:/src/.air.toml  # Ensure Air uses your config
