FROM golang:1.24

RUN apt update && apt upgrade -y && \
    apt install -y git \
    make openssh-client

WORKDIR /app 

RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh \
    && chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air


# Copy go.mod and go.sum files to the workspace
COPY go.mod go.sum ./

ENV GOFLAGS=-buildvcs=false

# Download all dependencies
RUN go mod download

# Copy the source from the current directory to the workspace
COPY . .

# Build the Go app
RUN go build -o main ./main.go

# Expose port 8080 to the outside world
EXPOSE 8080

CMD air
